services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shopio
      - POSTGRES_USER=shopio
      - POSTGRES_PASSWORD=12345
    env_file:
      - .env

  cache:
    image: redis
    restart: always
    volumes:
      - .data/cache:/data

  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=shopio.settings.prod
      - POSTGRES_DB=shopio
      - POSTGRES_USER=shopio
      - POSTGRES_PASSWORD=12345
    depends_on:
      - db
      - cache


    